### ISSUE TITLE
Possibility of running on windows

### ISSUE THREAD

**Issue by ahtsan** [zfw1226/gym-unrealcv#1]
Is it possible to run on windows? I am working on a very similar project based on windows (I can't get UE running probably on ubuntu 16.04).

**Comment by zfw1226** [comment]
It is possible to run it on windows because UE4 and Openai-gym both support windows. But currently, it is unable to run on Windows for that Nvidia-docker only run on Linux. In the future(maybe one or two weeks), We will release docker-free version which should be able to run on Windows.

**Comment by ahtsan** [comment]
That would be cool. I am very curious about how you transfer image from UE to unrealcv client. Currently my fps is very low.

**Comment by ahtsan** [comment]
Can I talk to you via email? Please.

**Comment by zfw1226** [comment]
To be honest, the frame rate of this project is only about 5fps.  We are also trying to improve it. 
It is fine, my email is zfw1226@gmail.com.
