### ISSUE TITLE
An error occurred when running demo

### ISSUE THREAD

**Issue by xiaotaonan** [zfw1226/gym-unrealcv#10]
ERROR:__init__:205:Can not connect to ('127.0.0.1', 9000)

**Comment by cslayers** [comment]
If you have not prepare the binary, see Section 'Prepare Unreal Binary' in README.

**Comment by xiaotaonan** [comment]
thanks

**Comment by rybsegszsyy** [comment]
Having the same problem today, how to solve it? I have prepared the binary by executing `python load_env.py -e RealisticRoom`.

**Comment by Damax18** [comment]
I have the same wrong message.
I install the gym-unrealcv by `pip install -e . `, download the RealisticRendering_RL_3.10.zip, unzip and move it to the UnrealEnv directory.  After run the random agent in docker-free way, the error message indicate that i can not connect to 127.0.0.1. 
python: 3.5
ubuntu:16.04
Thanks for your helps.
@zfw1226 @cslayers @jianhaifeng

**Comment by zfw1226** [comment]
Does the same occur when you running other environments? e.g. `UnrealArm-ContinuousPose-v1`

**Comment by Damax18** [comment]
> Does the same occur when you running other environments? e.g. `UnrealArm-ContinuousPose-v1`

after download and unzip the file, and change to other environment, the wrong message is 'gym.error.UnregisteredEnv: No registered env with id', the version of this code is v1.0, it seems the 'UnrealArm-ContinuousPose-v1' cannot be reconignized,  maybe the file -- gym-unrealcv/gym-unrealcv/__init__.py does not register these envs?

**Comment by zfw1226** [comment]
[Here](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/__init__.py#L33-L46) register the mentioned UnrealArm env.
Can you run any UE4 binary directly?
Do you run on Linux OS?

**Comment by Damax18** [comment]
now the rigister is right, the os is Ubuntu 16.04.5 LTS , and i can not run any UE4 binary directly, 
i just  run `pip install -e .` to install the gym-unrealcv,
run `python load_env.py` to load the binary file,
run `python random_agent.py` to active the environmet, then the error message still is :

python random_agent.py -e UnrealArm-ContinuousPose-v1
env_id: UnrealArm-ContinuousPose-v1
Running docker-free env, pid:6061
Please wait for a while to launch env......
exec nohup /data2/gym-unrealcv/gym_unrealcv/envs/UnrealEnv/unrealcv_binary/LinuxNoEditor/ArmUE4/Binaries/Linux/ArmUE4 OWI_RL
nohup: 忽略输入并把输出追加到'nohup.out'
127.0.0.1
ERROR:__init__:205:Can not connect to ('127.0.0.1', 9000)
ERROR:__init__:206:Error [Errno 111] Connection refused
UnrealCV server is not running. Please try again

That's all the steps i have done, whether I have missed some essential process?

**Comment by shuyuandeqipa** [comment]
您好，请问一下，我想要把桌面下面显示的虚拟环境可视化给关掉，应该怎么操作呢？

**Comment by zfw1226** [comment]
> 您好，请问一下，我想要把桌面下面显示的虚拟环境可视化给关掉，应该怎么操作呢？

在启动前，设置端口号即可，如: `export DISPLAY=:2`

**Comment by GradiusTwinbee** [comment]
Hi, I meet the same problem. Did anyone solve it?
