### ISSUE TITLE
If I can add some objects to the unreal environment, e.g.add a ball to the robotic arm env ?

### ISSUE THREAD

**Issue by cslayers** [zfw1226/gym-unrealcv#11]
This is a question, not an issue.
I want to add some objects to the environment, is that possible? 
Someone told me that it has to  have access to the UE4 project files, is that true?

**Comment by zfw1226** [comment]
Yes, it is true that you need to access the UE4 project to add some objects to the environment.

**Comment by cslayers** [comment]
Thanks.
