### ISSUE TITLE
Exiting abnormally

### ISSUE THREAD

**Issue by ybxbupt** [zfw1226/gym-unrealcv#12]
when I run "UnrealTrack-City1StefaniPath1-DiscreteColor-v1", some error occurred:

[2019.10.29-03.34.23:452][ 90]LogModuleManager: Shutting down and abandoning module PakFile (2)
[2019.10.29-03.34.23:457][ 90]LogExit: Exiting.
[2019.10.29-03.34.23:457][ 90]LogInit: Tearing down SDL.
Exiting abnormally (error code: 143)

**Comment by zfw1226** [comment]
Could you show more details about your environments ( OS, GPU, drivers, ...)?

**Comment by ybxbupt** [comment]
OS: ubuntu18.04
GPU: Nvidia1080ti
cuda9.0
python3.6
thank you very much!

**Comment by zfw1226** [comment]
Can you launch other environments, e.g. RealisticRoom? 
I guess that your issue is caused by Ubuntu18.04, if other environments can not be launched either.
Maybe you can try to use Nvidia-docker to launch the environment.
