### ISSUE TITLE
UnrealCV server is not running.

### ISSUE THREAD

**Issue by huxianer** [zfw1226/gym-unrealcv#13]
ERROR:__init__:205:Can not connect to ('127.0.0.1', 9005)
ERROR:__init__:206:Error [Errno 111] Connection refused
UnrealCV server is not running. Please try again

**Comment by xi-mao** [comment]
hi, i have the same problem, could u  tell me how to solve it?

**Comment by GradiusTwinbee** [comment]
Hi, I have the same problem too, could you tell me how to solve it?
@xi-mao @huxianer @zfw1226
