### ISSUE TITLE
About environments of active tracking

### ISSUE THREAD

**Issue by ReedZyd** [zfw1226/gym-unrealcv#15]
I wonder if I want to run the training code of project "End-to-end Active Object Tracking via Reinforcement Learning", which unreal binaries should I download? 

I downloaded all the binaries, but they didn't work. Is it because you modified the environment naming rules？

![image](https://user-images.githubusercontent.com/48706305/79043943-05c30800-7c35-11ea-991d-036d0889f5dd.png)

**Comment by zfw1226** [comment]
Yeah, the naming rule is updated. Please refer to https://github.com/zfw1226/gym-unrealcv/blob/v1.0/doc/EnvLists.md for the new environment naming rules.
