### ISSUE TITLE
Could you provide a detailed description on making the robot arm UE environment?

### ISSUE THREAD

**Issue by YantianZha** [zfw1226/gym-unrealcv#16]
Hello,

I have been struggling with how to make a robot environment that is similar to the robot arm example provided by gym-unrealcv. From the tutorial of either gym-unrealcv or unrealcv, it is not clear how to add robots with their meshes and kinematics/collision definitions into unreal engine so that a binary file can be compiled for gym-unrealcv. Usually we have urdf files to organize robot meshes and kinematics. Is there a way to import a robot by using their URDF files and linked meshes into unreal engine?

It would be great if a detailed description of how the robot arm was imported into unreal engine can be provided.

Thanks!

**Comment by zfw1226** [comment]
Hi,
As far as we know, the [URoboSim](https://github.com/robcog-iai/URoboSim) project would be helpful to you to import URDF files to UE4.

**Comment by YantianZha** [comment]
Thank you! I have tried using URoboSim as a project plugin. That said, I met lots of errors in the compiling phase. I suspect URoboSim is too old to use. Also the URoboSim mentions that URoboSim is deprecated and they are developing a newer version, but I cannot find it.
