### ISSUE TITLE
UnrealCV command

### ISSUE THREAD

**Issue by Calsia** [zfw1226/gym-unrealcv#17]
I found a command “vbp   *** **** ***”in this repository,which is not in unrealcv.
Could u teach me anything about that? 
thanks for any responds

**Comment by zfw1226** [comment]
It calls the blueprint function in UE4 via unrealcv. 
It is supported by the newer version of unrealcv, e.g. `4.25`, `4.22`, and `fast` branches.

**Comment by Calsia** [comment]
Thanks very much. It helps a lot
