### ISSUE TITLE
tracking 1v1 can't works well with my own scene

### ISSUE THREAD

**Issue by Calsia** [zfw1226/gym-unrealcv#18]
when i use ddpg(gym-unrealcv/example/ddpg/run.py) to train  "tracking_1v1"(gym-unrealcv/gym_unrealcv/envs/unrealcv_tracking_1v1.py) in the scene(Garage.json), everything goes well.
But when i train it in my own scene, the agent can just turn around forever.
So any suggestion ? or can you show me you scene projection code in ue? 

thanks for any responds

**Comment by zfw1226** [comment]
To get more details about Garage, you can independently launch the garage environment by running ``gym-unrealcv/gym_unrealcv/envs/UnrealEnv/Garage_2P/garage/Binaries/Linux/garage``. 
In fact,  the garage environment is only used for testing in our previous work, and the trackers are trained on the DuelingRoom with the environment augmentation.
In my view, a large learning rate/insufficient exploration/small memory size will lead the tracker to turn around.
Besides, the ddpg code is deprecated. You can try our recent A3C repo provided in [active_tracking_rl](https://github.com/zfw1226/active_tracking_rl) in your environment.

**Comment by Calsia** [comment]
thanks a lot,  i will try it again with your advice.
