### ISSUE TITLE
Run errors with gym-unrealcv for active object tracking

### ISSUE THREAD

**Issue by Dongzhou-1996** [zfw1226/gym-unrealcv#19]
partial errors output:
ERROR:__init__:205:Can not connect to ('127.0.0.1', 9000)
ERROR:__init__:206:Error [Errno 111] Connection refused

I wanna test the environment 'UnrealTrack-City1StefaniPath1-DiscreteColor-v1' for active object tracking, but it outputs errors. I have prepared the enviroment binaries by performing 'load_env.py', even all the binaries in 'load_env.py' have been downloaded. What can i do to fix this error?

kindly regards,
dong zhou

**Comment by zfw1226** [comment]
Hi Dong，
    It seems that you do not successfully launch the env binary.
    Can you explain more details about your software and hardware environments? e.g. OS, GPU version, if have a monitor connected to your computer?

**Comment by Dongzhou-1996** [comment]
> 
> 
> Hi Dong，
> It seems that you do not successfully launch the env binary.
> Can you explain more details about your software and hardware environments? e.g. OS, GPU version, if have a monitor connected to your computer?

Thanks for you reply. All the conditions you mentioned above are absolutely required. I have successfully performed the active object tracking code on gym_tvizdoom environment, however, it failed on gym_unrealcv environment. More details about my platform are list below:
OS: Ubuntu16.04
GPU: NVIDIA GeoForce RTX2080 Ti
Monitor: is connected.

And I am curious  about why it outputs the connection fault? Whether should I open the port of 9000 on host?

best regards, 
dong zhou

**Comment by zfw1226** [comment]
First, you need to check that if the binary can independently run on your computer. 
So can you see a window appear on your desktop when the connection fails? 
If not, can you run the binary indenpendently? 
Just go to `gym-unrealcv/gym_unrealcv/envs/UnrealEnv/` and run `./SplineCharacterF/SplineCharacterC/Binaries/Linux/SplineCharacterC`.
If the binary fails to launch,  the details of the errors will be reported in the terminal.

**Comment by Dongzhou-1996** [comment]
> First, you need to check that if the binary can independently run on your computer.
> So can you see a window appear on your desktop when the connection fails?
> If not, can you run the binary indenpendently?
> Just go to `gym-unrealcv/gym_unrealcv/envs/UnrealEnv/` and run `./SplineCharacterF/SplineCharacterC/Binaries/Linux/SplineCharacterC`.
> If the binary fails to launch, the details of the errors will be reported in the terminal.

Sincerely thanks for your help, I have figured out the problem which resulted from the remote connection to the host. However, there are still some errors when I perform ./SplineCharacterC/Linux/Binaries/SplineCharacterC, errors are listed below:

[2021.04.13-08.23.02:025][  0]LogStreaming: Error: Couldn't find file for package /Game/ThirdPersonBP/Blueprints/ThirdPersonGameMode requested by async loading code. NameToLoad: /Game/ThirdPersonBP/Blueprints/ThirdPersonGameMode
[2021.04.13-08.23.02:026][  0]LogStreaming: Error: Found 0 dependent packages...

In addition, the image displayed in window seems to be not rendered perfectly (attached below), I am not sure whether it correctly works or not.

![SplineCharacterC](https://user-images.githubusercontent.com/20870192/114523924-5c638780-9c77-11eb-8ee3-5b308439bd83.png)

**Comment by zfw1226** [comment]
1. You can ignore the mentioned error.
2. If you need run multiple workers, the start time of each worker needs to be at least 20 seconds apart, i.e. after launching one worker, please sleep for a while to launch another one. If not, the port conflict will make the connection fails.
3. The rendering is OK. Just move the camera up and the white floor will disappear.

**Comment by Dongzhou-1996** [comment]
Thanks again for your help, I would close this issue.
