### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by Christopheraburns** [zfw1226/gym-unrealcv#20]
[Question] I am evaluating gym-unrealcv for an upcoming project.  The project may have to run in a Windows environment.  Is there any dependencies in this project that would prevent me from creating a windows port?  Thanks

**Comment by zfw1226** [comment]
Hi, it is feasible to run gym-unrealcv in windows. You just need to prepare windows UE4 binary for your environment and try the `develop` branch.

**Comment by zfw1226** [comment]
@Christopheraburns I have updated the `v1.0' branch to support Windows. Meanwhile, I also released four Windows binary (   [FlexibleRoom](https://gym-unrealcv.oss-cn-beijing.aliyuncs.com/FlexibleRoom_Win_v0.zip), [UrbanCity](https://gym-unrealcv.oss-cn-beijing.aliyuncs.com/urbancity_win_v1.zip), [Garage](https://gym-unrealcv.oss-cn-beijing.aliyuncs.com/parkinglot_win_v1.zip), [Garden](https://gym-unrealcv.oss-cn-beijing.aliyuncs.com/neighborhood_win_v1.zip) ). These binaries are used by the active object tracking task. For convenience, you can use [load_env.py](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/load_env.py) script to prepare them in Windows.
