### ISSUE TITLE
the realated env setting file about paper 'Towards Distraction-Robust Active Visual Tracking'

### ISSUE THREAD

**Issue by Damax18** [zfw1226/gym-unrealcv#21]
thanks for your share about the interesting work  'Towards Distraction-Robust Active Visual Tracking'
can you update the realated env setting file about this paper?

best wishes~

**Comment by zfw1226** [comment]
Sorry for the late reply. 
I have updated the setting files for  'Towards Distraction-Robust Active Visual Tracking'.
