### ISSUE TITLE
Multi agent setting

### ISSUE THREAD

**Issue by JiayunjieJYJ** [zfw1226/gym-unrealcv#22]
I want to know does gym-unrealcv support multi agent setting? Is there any demo about it?

**Comment by zfw1226** [comment]
Yeah, thanks for your attention. 
There are a number of examples provided in gym-unrealcv for multi-agent usages, including multi-agent cooperation and competition. Referring to the [env init file](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/__init__.py), [L94-L114](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/__init__.py#L94-L114) are envs used for target-tracker competition introduced in [ICLR 2019](https://openreview.net/pdf?id=HkgYmhR9KX), [L117-L138](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/__init__.py#L117-L138) are envs used for multi-camera collaboration introduced in [AAAI 2020](https://arxiv.org/abs/2001.05161),  and [L141-L160](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/__init__.py#L141-L160) are envs used for cooperative-competitive multi-agent game introduced in [ICML 2021](https://arxiv.org/abs/2106.10110).

**Comment by JiayunjieJYJ** [comment]
> Yeah, thanks for your attention. There are a number of examples provided in gym-unrealcv for multi-agent usages, including multi-agent cooperation and competition. Referring to the [env init file](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/__init__.py), [L94-L114](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/__init__.py#L94-L114) are envs used for target-tracker competition introduced in [ICLR 2019](https://openreview.net/pdf?id=HkgYmhR9KX), [L117-L138](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/__init__.py#L117-L138) are envs used for multi-camera collaboration introduced in [AAAI 2020](https://arxiv.org/abs/2001.05161), and [L141-L160](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/__init__.py#L141-L160) are envs used for cooperative-competitive multi-agent game introduced in [ICML 2021](https://arxiv.org/abs/2106.10110).

@zfw1226 Thanks! And another question is does it support robot's 2D-laser input, because in real world there are many robots operating based on 2D laser input as well as vision input. And is there any demo about it?

**Comment by zfw1226** [comment]
> > Yeah, thanks for your attention. There are a number of examples provided in gym-unrealcv for multi-agent usages, including multi-agent cooperation and competition. Referring to the [env init file](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/__init__.py), [L94-L114](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/__init__.py#L94-L114) are envs used for target-tracker competition introduced in [ICLR 2019](https://openreview.net/pdf?id=HkgYmhR9KX), [L117-L138](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/__init__.py#L117-L138) are envs used for multi-camera collaboration introduced in [AAAI 2020](https://arxiv.org/abs/2001.05161), and [L141-L160](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/__init__.py#L141-L160) are envs used for cooperative-competitive multi-agent game introduced in [ICML 2021](https://arxiv.org/abs/2106.10110).
> 
> @zfw1226 Thanks! And another question is does it support robot's 2D-laser input, because in real world there are many robots operating based on 2D laser input as well as vision input. And is there any demo about it?

2D Laser is unavailable in the current version. Maybe you can use the depth image to simulate the 2D laser input.

**Comment by JiayunjieJYJ** [comment]
> > > Yeah, thanks for your attention. There are a number of examples provided in gym-unrealcv for multi-agent usages, including multi-agent cooperation and competition. Referring to the [env init file](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/__init__.py), [L94-L114](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/__init__.py#L94-L114) are envs used for target-tracker competition introduced in [ICLR 2019](https://openreview.net/pdf?id=HkgYmhR9KX), [L117-L138](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/__init__.py#L117-L138) are envs used for multi-camera collaboration introduced in [AAAI 2020](https://arxiv.org/abs/2001.05161), and [L141-L160](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/__init__.py#L141-L160) are envs used for cooperative-competitive multi-agent game introduced in [ICML 2021](https://arxiv.org/abs/2106.10110).
> > 
> > 
> > @zfw1226 Thanks! And another question is does it support robot's 2D-laser input, because in real world there are many robots operating based on 2D laser input as well as vision input. And is there any demo about it?
> 
> 2D Laser is unavailable in the current version. Maybe you can use the depth image to simulate the 2D laser input.

@zfw1226 Thanks. The depth image of RGBD is not very accurate and can't detect 360° surroundings. Alright, thank you anyway for your timely reply!

**Comment by JiayunjieJYJ** [comment]
@zfw1226 Hi, I want to ask can I use a 360 degree RGBD camera in gym unrealcv? Thanks!

**Comment by JiayunjieJYJ** [comment]
@zfw1226 "2D Laser is unavailable in the current version. Maybe you can use the depth image to simulate the 2D laser input." I get your idea !!!!
