### ISSUE TITLE
Errors with gym-unrealcv for active object tracking

### ISSUE THREAD

**Issue by Tie-1** [zfw1226/gym-unrealcv#24]
when i run 
`python train.py --num-workers=1 --env-id=Active-Tracking-Discrete-v0 --env-val-id=Active-Tracking-Discrete-v0 --model-id=convx2lstm --lr=0.00005 --log-dir=save/tmp --max-global-steps=250000000 --val-model-secs=-1 --max-val-episodes=40
`
for active object tracking, but it outputs errors. 

> [2022-04-03 19:35:26,597] Writing logs to file: /tmp/universe-1497164.log
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:197] Initialize GrpcChannelCache for job ps -> {0 -> 127.0.0.1:12222}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:197] Initialize GrpcChannelCache for job worker -> {0 -> localhost:12223}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:211] Started server with target: grpc://localhost:12223
[2022-04-03 19:35:26,608] Making new env: Active-Tracking-Discrete-v0
Traceback (most recent call last):
  File "/data/user18302012/anaconda3/envs/tracker/lib/python3.6/site-packages/gym/envs/registration.py", line 137, in spec
    return self.env_specs[id]
KeyError: 'Active-Tracking-Discrete-v0'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "worker.py", line 268, in <module>
    tf.app.run()
  File "/data/user18302012/anaconda3/envs/tracker/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "worker.py", line 257, in main
    run_worker(args, server, cluster)
  File "worker.py", line 36, in run_worker
    env = create_env(args.env_id, client_id=str(args.task), remotes=args.remotes)
  File "/data/user18302012/bishe/code/active_tracking_drl/envs.py", line 49, in create_env
    return create_unrealcv_env(env_full_name)
  File "/data/user18302012/bishe/code/active_tracking_drl/envs.py", line 120, in create_unrealcv_env
    env = gym.make(env_full_name)
  File "/data/user18302012/anaconda3/envs/tracker/lib/python3.6/site-packages/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/data/user18302012/anaconda3/envs/tracker/lib/python3.6/site-packages/gym/envs/registration.py", line 118, in make
    spec = self.spec(id)
  File "/data/user18302012/anaconda3/envs/tracker/lib/python3.6/site-packages/gym/envs/registration.py", line 147, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: Active-Tracking-Discrete-v0

I have prepared the enviroment binaries  RandomRoom、SplineCharacterA and SplineCharacterF. What can i do to fix this error?

Environments：
Ubuntu18.04
Python 3.6
tensorflow 0.12.1

thanks for any responds！

**Comment by zfw1226** [comment]
It seems that the `env-id` you used is not correct. Please refer to [this page](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/doc/EnvLists.md) for the correct `env-id` . 
Specifically, the `end-id` of the training environment is `UnrealTrack-City1StefaniPath1-DiscreteColor-v1` in the ICML 2018, and the random room is `UnrealTrack-RandoomRoom-DiscreteColor-v4` .

**Comment by Tie-1** [comment]
> It seems that the `env-id` you used is not correct. Please refer to [this page](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/doc/EnvLists.md) for the correct `env-id` . Specifically, the `end-id` of the training environment is `UnrealTrack-City1StefaniPath1-DiscreteColor-v1` in the ICML 2018, and the random room is `UnrealTrack-RandoomRoom-DiscreteColor-v4` .

Thank you for your reply! I make steps as you said, `python train.py --num-workers=1 --env-id=UnrealTrack-City1StefaniPath1-DiscreteColor-v1 --env-val-id=UnrealTrack-City1StefaniPath1-DiscreteColor-v1 --model-id=convx2lstm --lr=0.00005 --log-dir=save/tmp --max-global-steps=250000000 --val-model-secs=-1 --max-val-episodes=40`. But new questions occured in tmux 1:w-0:

> ERROR:__init__:205:Can not connect to ('127.0.0.1', 9000)
ERROR:__init__:206:Error [Errno 111] Connection refused  
UnrealCV server is not running. Please try again         

![X5HTW%Z4QEWQMWPZ8_I7N_O](https://user-images.githubusercontent.com/77917350/161936054-7825ecb7-6524-44c3-8a04-0171c4418430.png)
Can you give me some advice about it?

**Comment by zfw1226** [comment]
It shows that the unrealcv client in python fails to connect to the unrealcv server in UE4 environment. Do you see any new windows appearing on your desktop?

**Comment by Tie-1** [comment]
> It shows that the unrealcv client in python fails to connect to the unrealcv server in UE4 environment. Do you see any new windows appearing on your desktop?

Thank you for your reply! I found that the error because the server did not have a monitor. I try it on another computer with a monitor. But new errors occured:
![开始](https://user-images.githubusercontent.com/77917350/162204386-ba1580ea-8400-4588-b30f-c57eb67f9068.png)

0:ps

> ~/hzt/flour/active_tracking_drl$ CUDA_VISIBLE_DEVICES= /home/dell/anaconda3/envs/tracker/bin/python worker.py --log-dir save/tmp --env-id UnrealTrack-City1StefaniPath1-DiscreteColor-v1 --model-id convx2lstm --num-workers 1 --max-global-steps 250000000 --lr 5e-05 --ent-factor 0.01 --egreedy -1.0 --explore-factor 1.0 --job-name ps
/home/dell/anaconda3/envs/tracker/lib/python3.5/site-packages/autobahn/wamp/auth.py:40: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
  from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
/home/dell/anaconda3/envs/tracker/lib/python3.5/site-packages/universe/runtimes/__init__.py:7: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  spec = yaml.load(f)
[2022-04-07 20:27:39,255] Writing logs to file: /tmp/universe-739626.log
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:197] Initialize GrpcChannelCache for job ps -> {0 -> localhost:12222}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:197] Initialize GrpcChannelCache for job worker -> {0 -> 127.0.0.1:12223}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:211] Started server with target: grpc://localhost:12222

1:w-0

> [2022-04-07 20:27:39,262] Making new env: UnrealTrack-City1StefaniPath1-DiscreteColor-v1
Running docker-free env, pid:739730
Please wait for a while to launch env......
exec nohup /home/dell/hzt/flour/gym-unrealcv/gym_unrealcv/envs/UnrealEnv/SplineCharacterF/SplineCharacterC/Binaries/Linux/SplineCharacterC 
nohup: ignoring input and appending output to 'nohup.out'
127.0.0.1
INFO:__init__:192:Got connection confirm: b'connected to SplineCharacterC'
Traceback (most recent call last):
  File "worker.py", line 268, in <module>
    tf.app.run()
  File "/home/dell/anaconda3/envs/tracker/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "worker.py", line 257, in main
    run_worker(args, server, cluster)
  File "worker.py", line 36, in run_worker
    env = create_env(args.env_id, client_id=str(args.task), remotes=args.remotes)
  File "/home/dell/hzt/flour/active_tracking_drl/envs.py", line 49, in create_env
    return create_unrealcv_env(env_full_name)
  File "/home/dell/hzt/flour/active_tracking_drl/envs.py", line 120, in create_unrealcv_env
    env = gym.make(env_full_name)
  File "/home/dell/anaconda3/envs/tracker/lib/python3.5/site-packages/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/home/dell/anaconda3/envs/tracker/lib/python3.5/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/dell/anaconda3/envs/tracker/lib/python3.5/site-packages/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/home/dell/hzt/flour/gym-unrealcv/gym_unrealcv/envs/unrealcv_tracking_spline.py", line 70, in __init__
    self.reward_function = reward.Reward(setting)
  File "/home/dell/hzt/flour/gym-unrealcv/gym_unrealcv/envs/tracking/reward.py", line 11, in __init__
    self.dis_min = setting['min_distance']
KeyError: 'min_distance'

2:w-val

> /home/dell/anaconda3/envs/tracker/lib/python3.5/site-packages/autobahn/wamp/auth.py:40: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
  from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
/home/dell/anaconda3/envs/tracker/lib/python3.5/site-packages/universe/runtimes/__init__.py:7: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  spec = yaml.load(f)
[2022-04-07 20:27:49,284] Writing logs to file: /tmp/universe-739772.log
[2022-04-07 20:27:49,286] worker_val: val_model_secs < 0, no validating, exit...


3:tb

>(base) dell@dell: ~/hzt/flour/active_tracking_drl$ tensorboard --logdir save/tmp --port 12345
tensorboard: command not found

I also do not know the how to control the agent to move in a screen. The agent can only rely on the mouse to turn and can't move. 
Hope for your reply!

**Comment by zfw1226** [comment]
Sorry for the late reply!
 I have updated the environment setting files ([City1StefaniPath1.json](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/envs/setting/tracking_v0/City1StefaniPath1.json) and [City2MalcomPath2.json](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/envs/setting/tracking_v0/City2MalcomPath2.json)), and the error (`KeyError: 'min_distance'`) you reported should be fixed.

**Comment by VickyCas** [comment]
> Sorry for the late reply! I have updated the environment setting files ([City1StefaniPath1.json](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/envs/setting/tracking_v0/City1StefaniPath1.json) and [City2MalcomPath2.json](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/envs/setting/tracking_v0/City2MalcomPath2.json)), and the error (`KeyError: 'min_distance'`) you reported should be fixed.

Thank you very much！I will finish this issue later.

**Comment by Tie-1** [comment]
> Sorry for the late reply! I have updated the environment setting files ([City1StefaniPath1.json](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/envs/setting/tracking_v0/City1StefaniPath1.json) and [City2MalcomPath2.json](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/envs/setting/tracking_v0/City2MalcomPath2.json)), and the error (`KeyError: 'min_distance'`) you reported should be fixed.

Thank you for helping me!
