### ISSUE TITLE
What will 2D environments output

### ISSUE THREAD

**Issue by VickyCas** [zfw1226/gym-unrealcv#25]
Hi, Doctor Zhong! 
I want to try AD-VAT in 2D environment for active object tracking, but I don't know what will it outputs. When i run it, i find that tensorboard is Ok, but the pictures i could not find. What can i find these pictures?

kindly regards

**Comment by zfw1226** [comment]
Just add `--render` behind your execution commands. Note that the framerate will drop when rendering the graphics.

**Comment by VickyCas** [comment]
Thank you for your advice！
