### ISSUE TITLE
The problem about the fine-tuning of meta strategy

### ISSUE THREAD

**Issue by zhenzhenzhizhi** [zfw1226/gym-unrealcv#27]
Hello, the author, I want to ask a question about the training of the thesis of distractor. The second step of the meta strategy is to fine tune the teacher tracker. According to your tutorial, I put the “*. pth” file from the/log folder to a new folder, and then put the "nest. pth "file in another folder. Then use the command you give to train:
`python main.py --model simple-pos-act-lstm --tracker none --env UnrealTrackMulti-FlexibleRoomAdv-DiscreteColor-v1 --env-base UnrealTrackMulti-FlexibleRoomAdv-DiscreteColor-v1 --rnn-out 128 --seed 4 --seed-test 2   --train-mode 0 --norm-reward --aux attack-reward --lr 0.0005 --gpu-id 1 --old  ./old_oppent --load-model-dir ./new_model/new-201.pth
`
But it didn't produce any results. I don't know what's wrong.
![158ed965cc36b97e2550b2dea8dbe2d](https://user-images.githubusercontent.com/82042615/202394042-ccce5645-4a08-431c-a7f5-84b99701beb7.png)
![c3baee28b18d9d666a72b469e7dfe13](https://user-images.githubusercontent.com/82042615/202394096-46b99b76-fe71-46a4-beb0-0cdd7a241e0b.png)
![1b636cf1117a1ca4da9b1820b1c8d32](https://user-images.githubusercontent.com/82042615/202394130-51116d38-4f1d-48e8-9f6f-579dfee32a5c.png)

**Comment by zhenzhenzhizhi** [comment]
@zfw1226

**Comment by zfw1226** [comment]
Can you report the logs of your terminal after exiting (ctrl +c) the process? 

Note that this issue is about the [active_tracking_rl](https://github.com/zfw1226/active_tracking_rl) repo, it would be better to report this issue in that repo.

**Comment by zhenzhenzhizhi** [comment]
> Can you report the logs of your terminal after exiting (ctrl +c) the process?
> 
> Note that this issue is about the [active_tracking_rl](https://github.com/zfw1226/active_tracking_rl) repo, it would be better to report this issue in that repo.

Sorry, I will report this problem in the repo in active tracking.
