### ISSUE TITLE
Can not connect to ('127.0.0.1', 9000)

### ISSUE THREAD

**Issue by bx-li** [zfw1226/gym-unrealcv#29]
python main.py --shared-optimizer  --workers 6 --gpu-ids 0  --split --network tat-cnn-lstm --rnn-out 256 --entropy-target 0.05 --sleep-time 30 --env UnrealTrack-DuelingRoomPZR-DiscreteColor-v4 --env-base UnrealTrack-DuelingRoomNav-DiscreteColor-v4 --gray --rescale --lr 0.0001
Running docker-free env, pid:53780
Please wait for a while to launch env......
exec nohup /root/gym-unrealcv/gym_unrealcv/envs/UnrealEnv/DuelingRoom/tracking/Binaries/Linux/tracking 
nohup: ignoring input and appending output to 'nohup.out'
ERROR:__init__:205:Can not connect to ('127.0.0.1', 9000)
ERROR:__init__:206:Error [Errno 111] Connection refused
UnrealCV server is not running. Please try again
已经通过python load_env.py -e DuelingRoom安装过相关环境

**Comment by bx-li** [comment]
并且我单独启动环境时报错Refusing to run with the root privileges

**Comment by zfw1226** [comment]
> 并且我单独启动环境时报错Refusing to run with the root privileges

这已经说的很清楚了，UE4不支持用root权限启动，需要切换到一般user才行

**Comment by bx-li** [comment]
> > 并且我单独启动环境时报错Refusing to run with the root privileges
> 
> 这已经说的很清楚了，UE4不支持用root权限启动，需要切换到一般user才行

我用一般user单独启动环境还会报以下错误
Pooling OS allocations (pool size: 1408 MB, maximum allocations: 9502).
Using binned2.
Increasing per-process limit of core file size to infinity.
- Existing per-process limit (soft=18446744073709551615, hard=18446744073709551615) is enough for us (need only 18446744073709551615)
Project file not found: ../../../RealisticRendering/RealisticRendering.uprojectFatal error: [File:/media/yty/1C2ABACC2ABAA1E6/linux_ue4/UnrealEngine-4.16/Engine/Source/Runtime/PakFile/Private/IPlatformFilePak.cpp] [Line: 3621] 
Trailing magic number (795702095d) in '../../../RealisticRendering/Content/Paks/RealisticRendering-LinuxNoEditor.pak' is different than the expected one. Verify your installation.
Signal 11 caught.
Malloc Size=131076 LargeMemoryPoolOffset=131092 
CommonLinuxCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=196655 
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.

**Comment by zfw1226** [comment]
> 

请问设备的具体硬件条件是什么？有没有显示器？显卡和系统版本？

**Comment by bx-li** [comment]
> > 
> 
> 请问设备的具体硬件条件是什么？有没有显示器？显卡和系统版本？

是在云服务器上运行的，操作系统是ubuntu18.04，gpu是RTX 2080 Ti(11GB)，没有显示器，只有远程桌面

**Comment by zfw1226** [comment]
RealisticRender用的是UE4.16，不支持直接offscreen rendering。建议用FlexibleRoom等较新的环境

**Comment by zfw1226** [comment]
请看下单独启动binary的时候，具体报的是错误

**Comment by zfw1226** [comment]
在后缀加上 -opengl4 看看能不能启动？ 也就是执行 `./FlexibleRoom/trackingroom2/Binaries/Linux/trackingroom2 -opengl4`

**Comment by bx-li** [comment]
> 在后缀加上 -opengl4 看看能不能启动？ 也就是执行 `./FlexibleRoom/trackingroom2/Binaries/Linux/trackingroom2 -opengl4`

错误输出没有变化

**Comment by zfw1226** [comment]
请确认下显卡安装是否包含了渲染相关的组件，如OpenGL等。 初次使用建议先在本地有显示器的机器上尝试安装，或使用支持图形渲染的云服务器。

**Comment by bx-li** [comment]
> 请确认下显卡安装是否包含了渲染相关的组件，如OpenGL等。 初次使用建议先在本地有显示器的机器上尝试安装，或使用支持图形渲染的云服务器。

非常感谢您的耐心指导，我在服务器上安装图形渲染后问题解决。

**Comment by Damax18** [comment]
@zfw1226 @bx-li could you provide the information on how to install graphics rendering on a general server? or What keywords should I search for?
Thanks！

**Comment by zfw1226** [comment]
> @zfw1226 @bx-li could you provide the information on how to install graphics rendering on a general server? or What keywords should I search for? Thanks！

In general, you need to install opengl4 or Vulkan for rendering. Usually, they can be installed with the graphic driver.
You can refer to the keywords `offscreen rendering` or `rendering in headless server`.  [The document](https://carla.readthedocs.io/en/0.9.9/adv_rendering_options/#off-screen-mode) for CARLA has introduced it.
