### ISSUE TITLE
textures is not available to your platform

### ISSUE THREAD

**Issue by shubhamtrehan** [zfw1226/gym-unrealcv#30]
I tried to run SnowForest environment. But befroe that I need set up textures.
I ran "python3 load_env.py -e textures" but it says 
textures is not available to your platform

**Comment by zfw1226** [comment]
``python3 load_env.py -e Textures`` will work if you run it on Linux.

**Comment by shubhamtrehan** [comment]
Thanks.
Maybe that's the issue.
Since I am setting it up on windows
Any fix for windows?

**Comment by zfw1226** [comment]
Currently, we only released four Windows binary. They are `FlexibleRoom`, `UrbanCity`, `Garage`, and `Garden`. You can try to run them on Windows if you are convenient.

**Comment by shubhamtrehan** [comment]
Thanks. Will try them
