### ISSUE TITLE
Unable to run python3 random_agent.py -e UnrealTrack-City1StefaniPath1-DiscreteColor-v1

### ISSUE THREAD

**Issue by shubhamtrehan** [zfw1226/gym-unrealcv#31]
``
![image](https://github.com/zfw1226/gym-unrealcv/assets/40584612/b451a14a-7556-4de0-aae7-85847ab94bd1)

Installed the binaries before running. Binaries installed without any issues for SplineCharacterA.
But binary installation for UrbanCity didn't even install.

**Comment by zfw1226** [comment]
This is caused by the permission problem. You can add the permission by running `chmod -R 777 {path to the binary folder}` .
