### ISSUE TITLE
Which does tensorflow version match keras==1.2.0

### ISSUE THREAD

**Issue by iOkay** [zfw1226/gym-unrealcv#34]
hello! I'm reading 'Training a DQN Agent.'. 
I am using pyhton 3.10.13 with anaconda.  And I installed tensorflow by `pip install tensorflow`. Then it installed keras-2.15.0 tensorflow-2.15.0.
It conflicts with keras 1.2.0.

So which is the right version should I use?

**Comment by zfw1226** [comment]
Hi @iOkay , you can use Anaconda to build a new environment to install the Keras 1.2.0.   Note that the Keras examples are out-of-date (it was maintained many years ago). You can try the Pytorch A3C examples at https://github.com/zfw1226/active_tracking_rl .
