### ISSUE TITLE
关于unrealcv CTRL+C无法释放资源的问题

### ISSUE THREAD

**Issue by zhenzhenzhizhi** [zfw1226/gym-unrealcv#35]
非常感谢作者的更新，我感觉新版的环境运行起来比之前快了很多，而且突然挂进程的情况也没有了。
但是在运行干扰物那个代码时，遇到了一个问题，使用ctrl+c无法释放资源。表现为代码已经停止运行了，但是显卡资源和cpu资源都没有释放。需要手动kill进程才行。之前老版的代码没有出现类似的问题。
<img width="331" alt="微信图片_显卡" src="https://github.com/zfw1226/gym-unrealcv/assets/82042615/a1f85e3f-3a35-4ca3-a8a1-ab2bebda2483">

**Comment by zfw1226** [comment]
感谢关注。您说的释放问题已经在最新版的训练代码中更新，请参见https://github.com/zfw1226/active_tracking_rl/commit/067687360a927494486f1a0322f36fadd6e6b7b4  
简而言之，新版的环境关闭需要调用env.cloes()才能关闭线程及对应代码，因此当出现退出信号时同样需要调用env.close()
