### ISSUE TITLE
The gui is so small

### ISSUE THREAD

**Issue by wenjie-2000** [zfw1226/gym-unrealcv#36]
Hi, I wanna ask why the gui is so small? Do I need to install UE4 from ubuntu20?
<img width="1022" alt="image" src="https://github.com/zfw1226/gym-unrealcv/assets/62456817/5fc1bcc9-ba7c-46e7-95c2-4598ec7a2d0a">

**Comment by wukui-muc** [comment]
Hi, the default resolution setting is 240x240, if you want a bigger size, you need to change the configuration manually. https://github.com/zfw1226/gym-unrealcv/blob/110150b97c923377f46f401e30b25dc513d58340/gym_unrealcv/envs/unrealcv_tracking_general.py#L31C1-L31C39

**Comment by wenjie-2000** [comment]
Thank you! That's really help me~
