### ISSUE TITLE
unrealcv_cmd not found

### ISSUE THREAD

**Issue by Pranav-Saxena** [zfw1226/gym-unrealcv#38]
where can i get the unrealcv_cmd library? as mentioned in the doc https://github.com/zfw1226/gym-unrealcv/blob/v1.0/doc/addEnv.md 
for adding new env

**Comment by zfw1226** [comment]
I am sorry for not updating the document in time.
It should be revised to  ``from gym_unrealcv.envs.utils.unrealcv_basic import UnrealCv``.

**Comment by Pranav-Saxena** [comment]
Oh. Thanks!
