### ISSUE TITLE
OpenGL窗口黑屏

### ISSUE THREAD

**Issue by xiaohudieo** [zfw1226/gym-unrealcv#39]
运行random后OpenGL窗口显示黑屏

**Comment by zfw1226** [comment]
请问运行的是哪个环境，具体系统配置如何？

**Comment by xiaohudieo** [comment]
> 请问运行的是哪个环境，具体系统配置如何？

使用vmware workstation pro17虚拟机运行Linux环境，支持OpenGL4.3

**Comment by zfw1226** [comment]
您具体使用的是哪个gym环境？如果单独启动UE4 binary的时候是否出现黑屏？

**Comment by xiaohudieo** [comment]
python3 random_agent.py -e UnrealSearch-RealisticRoomDoor-DiscreteColor-v0运行示例这一句的时候，二进制文件RealisticRoom已加载

**Comment by zfw1226** [comment]
请尝试执行直接执行二进制文件`./gym_unrealcv/envs/UnrealEnv/RealisticRendering_RL_3.10/RealisticRendering/Binaries/Linux/RealisticRendering`

观察是否能正常启动，显示画面。如果不能，请查看窗口中具体的报错提示。

**Comment by xiaohudieo** [comment]
有窗口但仍黑屏，报错信息为LogStreaming:Error: Couldn't find file for package /Script/Engine requested by async loading code. NameToLoad: /Script/Engine

**Comment by zfw1226** [comment]
建议使用Windows（load_binary.py中已经提供了几个Windows的binary，可以尝试）或者换一台Linux主机。

**Comment by xiaohudieo** [comment]
好的
