### ISSUE TITLE
Camera's FOV in Environments

### ISSUE THREAD

**Issue by zzc0053** [zfw1226/gym-unrealcv#40]
Hi, thanks to your good work. But I still want to know how can I change the FOV in the Environment.

I tried to use the 'set_fov' method in 'unrealcv_basic.py', but an error was displayed. The error content is as follows: Failed to set FOV: error Can not find a handler for URI 'vset /camera/1/fov 45'.

When I used 'vset /camera/[id]/horizontal_fieldofview [FOV]' instead, the same error was displayed: Failed to set FOV: error Can not find a handler for URI 'vset /camera/1/horizontal_fieldofview 45'

How should I change the FOV value of the camera?

The version I used is as follows:
unrealcv version: 1.1.0
unrealcv plugin version: 0.3.10

**Comment by zfw1226** [comment]
Hi @zzc0053, You need to upgrade the Unrealcv plugin to a newer version, such as the `5.2` or `4.27` branch, as this command is added after `0.4`.

**Comment by zzc0053** [comment]
I'm sorry. How can I upgrade the Unrealcv plugin, I need to download the 5.2 branch, and then what next should do? For example, I'm using the 'RandomRoom' env.

**Comment by zfw1226** [comment]
Oh, if you use the pre-built binary, it is infeasible to upgrade the UnrealCV by yourself.
Fortunately, you can use the `FlexibleRoom` binary instead, an upgraded version of the `RandomRoom`.

**Comment by zzc0053** [comment]
Got it. Thanks.
