### ISSUE TITLE
error occurs when running random_agent.py

### ISSUE THREAD

**Issue by TONG369** [zfw1226/gym-unrealcv#8]
yangchengwu@robotvision-PowerEdge-T630:/home/dl/yangchengwu/Downloads/gym-unrealcv-0.2/example/random$ python random_agent.py -e 'Search-RrDoorDiscrete-v0'
Traceback (most recent call last):
  File "random_agent.py", line 2, in <module>
    import gym_unrealcv
ImportError: No module named 'gym_unrealcv'
yangchengwu@robotvision-PowerEdge-T630:/home/dl/yangchengwu/Downloads/gym-unrealcv-0.2/example/random$

**Comment by zfw1226** [comment]
It seems that you do not successfully install the `gym-unrealcv`.
You can follow the instructions on the readme to install it, i.e. running `pip install -e .`

**Comment by TONG369** [comment]
Ok, your reply I have received, thank you！！！
