### ISSUE TITLE
ERROR: cannot verify cs.jhu.edu's certificate, issued by '..RSA Server CA':

### ISSUE THREAD

**Issue by cslayers** [zfw1226/gym-unrealcv#9]
I encountered this error when i run the following command in my bash
`python load_env.py -e Arm`

**Comment by zfw1226** [comment]
Sorry, I can not reproduce your issue. 
Can you tell me more details about your software environment?

**Comment by cslayers** [comment]
Maybe Windows.
I run the command on Ubuntu 16 without a problem.
